name: Update File.json

on:
  workflow_dispatch:  # Memungkinkan eksekusi manual dari GitHub UI
  repository_dispatch:  # Dapat dipanggil dari frontend

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update file.json
        run: |
          echo '{"pesan": "Data baru dari GitHub Actions"}' > file.json
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add file.json
          git commit -m "Update file.json via GitHub Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.HAFIZ }}
